name: CI-PersonalSite

on:
  push

env:
  PATH_REACT:  ./personal-site

jobs:
  build:
    defaults:
      run:
        working-directory: $PATH_REACT

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout repo
    
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: print dir
      run: echo "$(ls)"

    - name: install react dependencies
      working-directory: $PATH_REACT
      run: npm install

    - name: build react client
      working-directory: $PATH_REACT
      run: npm run build
